-- 코스 좋아요(course_likes) — 좋아요/취소 토글 레코드.
-- user_id·course_id 는 cross-domain 이라 FK 를 두지 않는다(saved_courses 와 동일).
-- 취소는 하드 삭제라 소프트 삭제(deleted_at) 컬럼을 두지 않는다.
CREATE TABLE course_likes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    course_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- 좋아요 중복 방지: (user_id, course_id) 유니크. 서비스 사전검사(existsLike)와 별개로,
-- 동시 좋아요 경합(TOCTOU)에서도 코스당 좋아요 1개임을 DB 가 보장한다.
-- 위반(23505)은 GlobalExceptionHandler 가 테이블명(course_likes)으로 식별해 COURSE_ALREADY_LIKED 로 변환한다.
CREATE UNIQUE INDEX uq_course_likes_user_course
    ON course_likes (user_id, course_id);
